/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotingGuardian } from "./VotingGuardian";
export * as factories from "./factories";
export { VotingGuardian__factory } from "./factories/VotingGuardian__factory";
